version: "3.9"
services:
  backend:
    build:
      context: simple-status-api
      image: simple-status-api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
  frontend:
    build:
      context: simple-status-ui
      image: simple-status-ui
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
