version: "3.9"
services:
  backend:
    container_name: simple-status-api
    build:
      context: simple-status-api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
  frontend:
    container_name: simple-status-ui
    build:
      context: simple-status-ui
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
